import { Globe, Github, Server, Network, Container, Mail, LayoutDashboard, Terminal, Cloud, Database, TrendingUp, Sparkles, Search, Bot } from 'lucide-react';
import { NavItem } from './types';

export const SITE_CONFIG = {
  name: 'at9.net 导航站',
  shortName: 'at9.net',
  domains: ['www.at9.net', 'at9.net'],
  titles: ['DevOps Engineer', 'Cloud Native Explorer', 'AI Enthusiast', 'Vibe Coding'],
  tagline: '聚合个人项目、在线工具与云端资产的专业导航入口。',
};

export const STATS = {
  totalSites: 17,
  activeProjects: 8,
  mirrorServices: 3,
  openSourceRepos: 26,
};

export const NAV_LINKS: NavItem[] = [
  {
    id: 'home',
    title: 'at9.net Home',
    url: 'https://at9.net',
    description: '个人数字资产主控台与导航入口，所有子站点的起点。',
    icon: Globe,
    category: 'Official',
    color: 'text-emerald-400',
    badge: 'PORTAL',
    isFeatured: true,
  },
  {
    id: '9deck',
    title: '9Deck Dashboard',
    url: '/9deck/',
    description: '云端个人数字资产主控台，包含开源项目、动态与监控。',
    icon: LayoutDashboard,
    category: 'Official',
    color: 'text-emerald-400',
    badge: 'DASHBOARD',
    isFeatured: true,
  },
  {
    id: 'blog',
    title: 'Tech Blog',
    url: 'https://blog.at9.net',
    description: '技术博客，记录运维、AI 与云原生学习之路。',
    icon: Terminal,
    category: 'Official',
    color: 'text-cyan-400',
    isFeatured: true,
  },
  {
    id: 'github',
    title: 'GitHub',
    url: 'https://github.com/htazq',
    description: '开源项目、代码仓库与外部贡献聚合。',
    icon: Github,
    category: 'Social',
    color: 'text-white',
    tags: ['Open Source', 'Portfolio'],
  },
  {
    id: 'github-at9',
    title: 'GitHub.at9.net',
    url: 'https://github.at9.net',
    description: '最新上线的 GitHub 聚合导航与镜像加速入口。',
    icon: Github,
    category: 'Mirror',
    color: 'text-purple-400',
    badge: 'NEW',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 'cnb',
    title: 'CNB 平台',
    url: 'https://cnb.cool/htazq',
    description: 'Cloud Native Build 平台，CI/CD 与代码托管。',
    icon: Cloud,
    category: 'Social',
    color: 'text-orange-400',
  },
  {
    id: 'docker',
    title: 'Docker Mirror',
    url: 'https://docker.at9.net',
    description: 'Docker 镜像加速服务，快速拉取常用镜像。',
    icon: Container,
    category: 'Mirror',
    color: 'text-blue-500',
    badge: 'MIRROR',
    isFeatured: true,
  },
  {
    id: 'ip',
    title: 'View-My-IP',
    url: 'https://ip.at9.net',
    description: '快速获取本机公网 IP、地理位置与网络信息。',
    icon: Network,
    category: 'Tool',
    color: 'text-green-400',
    badge: 'NETWORK',
  },
  {
    id: 'gh-proxy',
    title: 'GitHub Proxy',
    url: 'https://gh-proxy.at9.net/',
    description: 'GitHub 文件与 release 加速下载服务。',
    icon: Server,
    category: 'Mirror',
    color: 'text-purple-400',
  },
  {
    id: 'openclaw',
    title: 'OpenClaw',
    url: 'https://openclaw.ai',
    description: '跨平台个人 AI 助手，Any OS, Any Platform。',
    icon: Bot,
    category: 'AI',
    color: 'text-pink-400',
    tags: ['AI', 'Assistant'],
  },
  {
    id: 'tradingagents',
    title: 'TradingAgents AShare',
    url: 'https://app.510168.xyz',
    description: 'A 股多智能体投研系统，AI Agent 模拟机构协作。',
    icon: TrendingUp,
    category: 'Finance',
    color: 'text-amber-400',
    tags: ['Finance', 'Multi-Agent'],
  },
  {
    id: 'nofx',
    title: 'Vergex / NoFX',
    url: 'https://vergex.trade',
    description: 'AI 交易终端助手，覆盖美股、商品、外汇与加密货币。',
    icon: TrendingUp,
    category: 'Finance',
    color: 'text-amber-400',
    tags: ['Trading', 'Quant'],
  },
  {
    id: 'imgbed',
    title: 'CloudFlare ImgBed',
    url: 'https://cfbed.sanyue.de',
    description: '基于 Cloudflare 的无服务器开源图床与文件托管。',
    icon: Database,
    category: 'Storage',
    color: 'text-sky-400',
    tags: ['Cloudflare', 'Serverless'],
  },
  {
    id: 'zfile',
    title: 'ZFile',
    url: 'https://www.zfile.vip',
    description: '在线云盘、私有云、对象存储与文件管理方案。',
    icon: Database,
    category: 'Storage',
    color: 'text-sky-400',
  },
  {
    id: 'chatgpt-web',
    title: 'ChatGPT Web Proxy',
    url: 'https://chatgpt-web-midjourney-proxy-five-zeta.vercel.app',
    description: 'ChatGPT + Midjourney 代理前端，AI 对话入口。',
    icon: Sparkles,
    category: 'AI',
    color: 'text-pink-400',
  },
  {
    id: 'bing-proxy',
    title: 'Bing AI Proxy',
    url: 'https://go-proxy-bingai-vercel-htazq.vercel.app',
    description: 'Go Proxy BingAI Vercel 镜像，New Bing 对话入口。',
    icon: Search,
    category: 'AI',
    color: 'text-pink-400',
  },
  {
    id: 'email',
    title: 'Email',
    url: 'mailto:at9net@gmail.com',
    description: '商务合作与技术交流，欢迎发邮件。',
    icon: Mail,
    category: 'Social',
    color: 'text-red-400',
  },
];

export const CATEGORIES: { id: NavItem['category']; label: string; color: string }[] = [
  { id: 'Official', label: '官方站点', color: 'bg-emerald-500/20 text-emerald-400' },
  { id: 'Mirror', label: '镜像服务', color: 'bg-purple-500/20 text-purple-400' },
  { id: 'Tool', label: '实用工具', color: 'bg-green-500/20 text-green-400' },
  { id: 'AI', label: 'AI 项目', color: 'bg-pink-500/20 text-pink-400' },
  { id: 'Finance', label: '金融量化', color: 'bg-amber-500/20 text-amber-400' },
  { id: 'Storage', label: '存储托管', color: 'bg-sky-500/20 text-sky-400' },
  { id: 'Social', label: '社交平台', color: 'bg-cyan-500/20 text-cyan-400' },
  { id: 'Project', label: '开源项目', color: 'bg-orange-500/20 text-orange-400' },
  { id: 'Dev', label: '开发资源', color: 'bg-blue-500/20 text-blue-400' },
];
